version: '3'

services:

  opencr:
    container_name: opencr
    image: intrahealth/opencr
    ports:
      - "3000:3000"
    depends_on:
      - fhir
      - es01
    restart: always
    environment:
      - NODE_ENV=cicd
    networks: 
      - opencr

  fhir:
    container_name: hapi-fhir
    image: hapiproject/hapi:v5.1.0
    ports:
      - "8080:8080"
    networks:
      - opencr

  es01:
    image: intrahealth/elasticsearch:latest
    container_name: es01
    environment:
      - node.name=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - opencr


  kib01:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
      ELASTICSEARCH_SSL_VERIFICATIONMODE: none
    networks:
      - opencr

volumes:
  data01:
    driver: local

networks:
  opencr:
    driver: bridge